### ISSUE TITLE
Instagram links not showing content

### ISSUE THREAD

**Issue by ChaseS-Dev** [seriaati/embed-fixer#30]
As stated the links are just showing this 
![image](https://github.com/seriaati/embed-fixer/assets/15176850/04bbbbdb-0bb1-4517-9836-f221c1316802)

**Comment by seriaati** [comment]
Noted.

**Comment by seriaati** [comment]
Seems to be a known issue: https://github.com/Wikidepia/InstaFix/issues/96
Will need to wait for them to fix, I am not responsible for maintaining the fixes.
