### ISSUE TITLE
Twitch embeds

### ISSUE THREAD

**Issue by icray1** [seriaati/embed-fixer#55]
Hello, I was wondering if you could add twitch embeds as well.  There are two different twitch share methods from mobile and desktop, m.twitch.tv/clip/ and clips.fxtwitch.tv/ the result should be clips.fxtwitch.tv/ for both inputs. A working example would be https://clips.twitch.tv/ColdbloodedPowerfulDurianPupper-zS2syJ91CNRIqC4v?tt_content=url&tt_medium=clips_api to https://clips.fxtwitch.tv/ColdbloodedPowerfulDurianPupper-zS2syJ91CNRIqC4v?tt_content=url&tt_medium=clips_api . Thanks!

**Comment by seriaati** [comment]
@icray1 Is this fix open-sourced? I can't seem to find information about it.

**Comment by icray1** [comment]
Sorry, I looked as well I can't find anything about this fixer.

**Comment by seriaati** [comment]
I'm not gonna add this fix then, it may have risk of containing malicious links.

**Comment by seriaati** [comment]
@icray1 Support for twitch clip embeds is added, I decided to make my own fixer: [fxtwitch](https://github.com/seriaati/fxtwitch).
