### ISSUE TITLE
Bluesky Support

### ISSUE THREAD

**Issue by FantasticMrScott** [seriaati/embed-fixer#59]
https://github.com/Rapougnac/VixBluesky

Can you add support for Bluesky such as the code linked?

**Comment by seriaati** [comment]
Initial support for embed fix is added (https://github.com/seriaati/embed-fixer/commit/1d86f9b121321bc1e4b54b08a07d4d48f291ef70); media extraction feature not yet, need to wait for response on this issue: https://github.com/Rapougnac/VixBluesky/issues/21
