### ISSUE TITLE
[FEATURE REQUEST] Embed-Fixer available as a Redbot Cog

### ISSUE THREAD

**Issue by Ceddicedced** [seriaati/embed-fixer#62]
Hey there! 👋

First off, thanks for making embed-fixer—it’s a super useful tool!

I was wondering if you’d consider adapting it to work as a cog for Redbot (the bot framework a lot of Discord servers use for custom commands and features). Having embed-fixer as a cog would make it way easier for Redbot users to integrate it right into their bot setups without needing to run an extra bot.

**Comment by seriaati** [comment]
Hi @Ceddicedced, thanks for writing this feature request. Unfortunately, I am not very interested in the idea of writing the bot as a Redbot cog, so I will mark this issue as not planned; nevertheless, feel free to re-open the issue if you want to add something to it.

Reason:
Just to be clear, this is my first time hearing about the Redbot, so I might have some misunderstandings about it. My understanding is that each functionality of the Redbot is written in one Python file, like `music.py` would contain all logics and utils for the music function.
To make embed fixer a Redbot cog, I would need to condense the entire bot's logic, from guild settings to regex matching into **one** Python file. Although this is theoretically possible, I a) don't like the idea and b) would need to maintain a separate version of the bot (the cog version) which I see has no benefits at all.
