### ISSUE TITLE
disable adding ❌ reaction

### ISSUE THREAD

**Issue by o-az** [seriaati/embed-fixer#69]
Is there a setting to disable the ❌ auto reaction? It's useful but not in a specific case I'm in atm

**Comment by studiobutter** [comment]
Can you explain the case? Usually X icon is needed to delete the message tho I don't understand why would you want to disable the Auto Reaction?

**Comment by o-az** [comment]
I have no need for it as I very rarely delete and if I do want to I can do it the same way I delete any message. 

Plus I have 1 server with thousands of members, way too much work to tell every new joiner "don't press that reaction"

**Comment by seriaati** [comment]
Yeah but what if your server member wants to delete the message sent by the webhook?

**Comment by studiobutter** [comment]
I feel like this is something you would use in a Private Server like an Archive or something right?

**Comment by o-az** [comment]
> Yeah but what if your server member wants to delete the message sent by the webhook?

Only I post the videos/links. Users are not allowed to share urls in this server

**Comment by seriaati** [comment]
sounds like a valid use case

**Comment by seriaati** [comment]
Added
